In [2]:
import pandas as pd

In [3]:
csv = pd.read_csv('CompleteDataSet.csv')

/var/folders/36/khn_y8zn7qqflczfpst8cbfc0000gn/T/ipykernel_77115/21958967.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  csv = pd.read_csv('CompleteDataSet.csv')

In [4]:
csv

,TimeStamps,AnkleAccelerometer,Unnamed: 2,Unnamed: 3,AnkleAngularVelocity,Unnamed: 5,Unnamed: 6,AnkleLuminosity,RightPocketAccelerometer,Unnamed: 9,...,Infrared1,Infrared2,Infrared3,Infrared4,Infrared5,Infrared6,Subject,Activity,Trial,Tag
0,NaN,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),illuminance (lx),x-axis (g),y-axis (g),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-07-04T12:04:17.738369,-1.005,0.229,-0.083,-0.671,0.488,-2.683,0,-0.981,0.26,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
2,2018-07-04T12:04:17.790509,-1.005,0.228,-0.082,-3.415,-0.549,0.122,0,-0.981,0.26,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
3,2018-07-04T12:04:17.836632,-1.005,0.231,-0.079,-2.622,-1.402,-0.549,0,-0.975,0.282,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
4,2018-07-04T12:04:17.885262,-1.005,0.231,-0.079,-2.561,-2.195,-1.22,0,-0.973,0.301,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294674,2018-07-12T12:18:28.783680,0.247,0.948,0.12,-1.646,0.488,-0.061,311.969,-0.479,-0.118,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0
294675,2018-07-12T12:18:28.832811,0.247,0.952,0.121,-1.037,0.732,-0.244,311.969,-0.488,-0.119,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0
294676,2018-07-12T12:18:28.892470,0.246,0.952,0.115,-0.61,0.732,-0.061,311.969,-0.488,-0.119,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0
294677,2018-07-12T12:18:29.025324,0.249,0.949,0.12,-0.854,0.427,-0.061,311.969,-0.472,-0.116,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0
294678,2018-07-12T12:18:29.070446,0.249,0.949,0.12,-0.61,0.915,0.122,311.969,-0.472,-0.116,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0

In [5]:
csv[
    (csv['Activity'] == 1) &
    (csv['Subject'] == 7) &
    (csv['Trial'] == 1)
][['Tag', 'TimeStamps']]

         Tag                  TimeStamps
103166   7.0  2018-07-06T12:42:37.360741
103167   7.0  2018-07-06T12:42:37.403858
103168   7.0  2018-07-06T12:42:37.450983
103169   7.0  2018-07-06T12:42:37.499615
103170   7.0  2018-07-06T12:42:37.545739
...      ...                         ...
103345  11.0  2018-07-06T12:42:47.013975
103346  11.0  2018-07-06T12:42:47.101209
103347  11.0  2018-07-06T12:42:47.170896
103348  11.0  2018-07-06T12:42:47.234065
103349  11.0  2018-07-06T12:42:47.280423

[184 rows x 2 columns]

In [6]:
# See the statiscal distribution of the dataset
print(csv['AnkleAccelerometer'][1:].astype(float).mean())
print(csv['AnkleAccelerometer'][1:].astype(float).std())
print(csv['AnkleAccelerometer'][1:].astype(float).max())
print(csv['AnkleAccelerometer'][1:].astype(float).min())

-0.47433101894271024
0.7648491739978542
3.678
-4.162

In [7]:
sorted(csv['Tag'].unique())

[np.float64(nan),
 np.float64(1.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(6.0),
 np.float64(7.0),
 np.float64(8.0),
 np.float64(9.0),
 np.float64(10.0),
 np.float64(11.0),
 np.float64(20.0)]

In [8]:
csv.loc[csv['Tag'] == 20, 'Tag'] = 2
csv

,TimeStamps,AnkleAccelerometer,Unnamed: 2,Unnamed: 3,AnkleAngularVelocity,Unnamed: 5,Unnamed: 6,AnkleLuminosity,RightPocketAccelerometer,Unnamed: 9,...,Infrared1,Infrared2,Infrared3,Infrared4,Infrared5,Infrared6,Subject,Activity,Trial,Tag
0,NaN,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),illuminance (lx),x-axis (g),y-axis (g),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-07-04T12:04:17.738369,-1.005,0.229,-0.083,-0.671,0.488,-2.683,0,-0.981,0.26,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
2,2018-07-04T12:04:17.790509,-1.005,0.228,-0.082,-3.415,-0.549,0.122,0,-0.981,0.26,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
3,2018-07-04T12:04:17.836632,-1.005,0.231,-0.079,-2.622,-1.402,-0.549,0,-0.975,0.282,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
4,2018-07-04T12:04:17.885262,-1.005,0.231,-0.079,-2.561,-2.195,-1.22,0,-0.973,0.301,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294674,2018-07-12T12:18:28.783680,0.247,0.948,0.12,-1.646,0.488,-0.061,311.969,-0.479,-0.118,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0
294675,2018-07-12T12:18:28.832811,0.247,0.952,0.121,-1.037,0.732,-0.244,311.969,-0.488,-0.119,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0
294676,2018-07-12T12:18:28.892470,0.246,0.952,0.115,-0.61,0.732,-0.061,311.969,-0.488,-0.119,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0
294677,2018-07-12T12:18:29.025324,0.249,0.949,0.12,-0.854,0.427,-0.061,311.969,-0.472,-0.116,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0
294678,2018-07-12T12:18:29.070446,0.249,0.949,0.12,-0.61,0.915,0.122,311.969,-0.472,-0.116,...,1.0,1.0,1.0,0.0,1.0,1.0,17.0,11.0,3.0,11.0

In [9]:
csv[csv['Tag']==20]

Empty DataFrame
Columns: [TimeStamps, AnkleAccelerometer, Unnamed: 2, Unnamed: 3, AnkleAngularVelocity, Unnamed: 5, Unnamed: 6, AnkleLuminosity, RightPocketAccelerometer, Unnamed: 9, Unnamed: 10, RightPocketAngularVelocity, Unnamed: 12, Unnamed: 13, RightPocketLuminosity, BeltAccelerometer, Unnamed: 16, Unnamed: 17, BeltAngularVelocity, Unnamed: 19, Unnamed: 20, BeltLuminosity, NeckAccelerometer, Unnamed: 23, Unnamed: 24, NeckAngularVelocity, Unnamed: 26, Unnamed: 27, NeckLuminosity, WristAccelerometer, Unnamed: 30, Unnamed: 31, WristAngularVelocity, Unnamed: 33, Unnamed: 34, WristLuminosity, BrainSensor, Infrared1, Infrared2, Infrared3, Infrared4, Infrared5, Infrared6, Subject, Activity, Trial, Tag]
Index: []

[0 rows x 47 columns]

In [10]:
import numpy as np
print(np.array(sorted(csv['Tag'][1:].unique().astype(int))))

[ 1  2  3  4  5  6  7  8  9 10 11]

In [12]:
csv.columns = csv.columns.str.replace(r'^Unnamed.*', '', regex=True)

In [13]:
csv.to_csv('CompleteDataSet.csv', index=False)

In [ ]:

from pathlib import Path


Path('2018-07-06T12_42_37.450983.png').stem

'2018-07-06T12_42_37.450983'